[package]
name = "bubble_sort"
version = "0.1.0"
authors = ["Cake42 <heitortoledo@hotmail.com>"]
edition = "2018"

[dependencies]
rand = "0.4.0"
time = "0.1.42"

[lib]
path = "src/bubble_sort.rs"

[[bin]]
name = "bubble_sort"
path = "src/bubble_sort.rs"
